### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by minhnimble** [ducbm051291/NimbleSurvey#2]
I notice that you made some good choices for the UI implementations by effectively utilizing the common 3rd party libraries. At the same time, there are some noticeable issues with the current implementation and I would like to list them down as follow:

- On the Login screen:

  1. The current status bar color is hard to see with the dark navigation bar and dark content below.
  2. The text color of the password textfield is incorrectly set to black while the design is white.
  3. The keyboard with the top toolbar partially covers the Login button and make it hard for users to input their credentials in one go. Maybe we can handle to move the textfields and the button up while the keyboard is active. What do you think?
  <img src="https://user-images.githubusercontent.com/70877098/158753750-cffabca9-d0c3-4f9d-a8c6-435024b59e4a.png" width="300">

  4. The tint color of the textfields are in default blue. What do you think about setting it white for matching our design?
  <img src="https://user-images.githubusercontent.com/70877098/158754018-793a86c3-7e9e-44e7-a141-5611fe0110fe.png" width="300">

  5. When providing an invalid email format string into the email textfield, the Login button is still enabled and thus the login API still gets called and it always results in an error message. What is your opinion on checking for the validity of the email before calling the API as well?
  <img src="https://user-images.githubusercontent.com/70877098/158754371-7404d195-4d05-4c27-ad0e-13508a758b5b.png" width="300">

- On the Surveys List screen:

  1. There is an overlapping issue that the initial shimmer loading indicator is shown at the same time with the `SVProgressHUD` loading indicator. I believe it is good to show only the shimmer loading indicator and can omit the other one. What do you think?
  2. The initial shimmer loading indicator should have animations but with your implementation it is a static screen at this point. In case you are not familiar with a skeleton skimmer, you can refer to this [library](https://github.com/omerfarukozturk/UIView-Shimmer) for more information. Can you update the application to use an animated shimmer loading indicator here? 🙏
  3. There is no Today text and current date label found as per design.
  4. On non-notch devices (iPhone 5/SE, 8, etc.), the shimmer loading view has weird leading and trailing white space.
  <img src="https://user-images.githubusercontent.com/70877098/158755183-e0d8ee0e-c352-4ad6-b422-fba50b0a176d.png" width="300">

  5. Tapping on the page control will only update the page indicator highlight, not the corresponding survey displaying content.
  6. Swiping very fast to the next survey item won't update the page indicator immediately for every new page until user stops the fast swiping.

  https://user-images.githubusercontent.com/70877098/158757119-ff72db36-53f9-4d4e-892f-749221f87f77.mov

  7. When there is no network connection, there will be an error prompt shown from the API and the screen will appear as white. There is nothing we can do even if we resume the connection back and we have to kill and restart the application at this point. Do you have any suggestion to handle the issue better and remove this blocking experience?

  https://user-images.githubusercontent.com/70877098/158758012-73f18097-43d9-47c1-a664-c64b62088452.mov

  8. I think we could add some dark overlay over the image in order to make text more legible because in brighter background images, we would not be able to see the text clearly as texts are in white. What do you think? 🤔

**Comment by ducbm051291** [comment]
On the Login screen:

1/The current status bar color is hard to see with the dark navigation bar and dark content below.
+ Yes, We should change the status bar style to light.

2/ The text color of the password textfield is incorrectly set to black while the design is white.
+ I missed this. Nice catch.

3/ The keyboard with the top toolbar partially covers the Login button and make it hard for users to input their credentials in one go. Maybe we can handle to move the textfields and the button up while the keyboard is active. What do you think?
+ Most of case I will depend on third party IQKeyboardManager. For this case, we should observe when keyboard appear and get the keyboard height and push the UI up a little bit. 

4/The tint color of the textfields are in default blue. What do you think about setting it white for matching our design?
+ Yes, we should do this.

5/When providing an invalid email format string into the email textfield, the Login button is still enabled and thus the login API still gets called and it always results in an error message. What is your opinion on checking for the validity of the email before calling the API as well?
+ In usual, QC definitely catches this. Yes, we should validate the email using regex and display a warning message to let user know that they input a invalidated email.

6/On the Surveys List screen:
There is an overlapping issue that the initial shimmer loading indicator is shown at the same time with the SVProgressHUD loading indicator. I believe it is good to show only the shimmer loading indicator and can omit the other one. What do you think?
The initial shimmer loading indicator should have animations but with your implementation it is a static screen at this point. In case you are not familiar with a skeleton skimmer, you can refer to this [library]
(https://github.com/omerfarukozturk/UIView-Shimmer)[](https://user-images.githubusercontent.com/70877098/158755183-e0d8ee0e-c352-4ad6-b422-fba50b0a176d.png) for more information. Can you update the application to use an animated shimmer loading indicator here? 🙏
+ In the start, I use loading indicator only, but I see the white blank so I add the lazy load image ^^ Ok. I will 

7/There is no Today text and current date label found as per design.
+ I read the tech document very carefully, it doesn't require it. only ask for Cover image (background), Name (in bold), Description. I can update it later.

8/On non-notch devices (iPhone 5/SE, 8, etc.), the shimmer loading view has weird leading and trailing white space.
+ It's aspect fit not scale to fill. I will replace it by the Shimmer library you posted above.

9/ Tapping on the page control will only update the page indicator highlight, not the corresponding survey displaying content.
+ I totally miss this, good one. 

10/Swiping very fast to the next survey item won't update the page indicator immediately for every new page until user stops the fast swiping.
+ I think this is usual behavior, but we can improve this. Currently we only update when scrollViewDidEndDecelerating.

11/ When there is no network connection, there will be an error prompt shown from the API and the screen will appear as white. There is nothing we can do even if we resume the connection back and we have to kill and restart the application at this point. Do you have any suggestion to handle the issue better and remove this blocking experience?
+ We observe the network, if there's no internet connection and the list is empty, we will display a message to let user know. When internet connection restore, we check if the list is empty, we will retry to load the survey list.

12/I think we could add some dark overlay over the image in order to make text more legible because in brighter background images, we would not be able to see the text clearly as texts are in white. What do you think? 🤔
+ I saw this issue and did add a black overlay with opacity 20% but seem it's not dark enough 👍

**Comment by minhnimble** [comment]
Thank you for your quick responses. Most of the cases your responses look good to me and I can't wait to see your fixes 🙏. Regarding the following points, I would like to answer to you as follow:

> I read the tech document very carefully, it doesn't require it. only ask for Cover image (background), Name (in bold), Description. I can update it later.

→ Yup you are right on this part, it is actually a minor thing and you can choose to skip if you don't want to do it, not a big deal for me 👌

> We observe the network, if there's no internet connection and the list is empty, we will display a message to let user know. When internet connection restore, we check if the list is empty, we will retry to load the survey list.

→ I am wondering if there is any other method in case we are unable to load the list even with proper connection and we want to retry the load again. What do you think? 🤔 

> I saw this issue and did add a black overlay with opacity 20% but seem it's not dark enough 

→ Oh you are right, now I realize you added the layer, but it is not noticeable at first. Finding the right ratio is indeed hard here as too high opacity will make it hard to see the images 😓. So is there any better option you can think of to solve this issue?

**Comment by ducbm051291** [comment]
I just created Pull Request here https://github.com/ducbm051291/NimbleSurvey/pull/8 to fix almost things you mention above and in another issues (Check the PR description for changed logs). Please take a look and review it when you have free time. Thank you. Happy weekend ;)

**Comment by minhnimble** [comment]
Good morning, Duc 👋

Thank you for the fast pull request! By the way I see that you have created a separate PR but you haven't merged it into the main branch yet. Please go ahead and merge if you think your changes are ready to review and I will follow up from there, since right now I don't have the option to merge 🙏
![Screen Shot 2022-03-21 at 09 38 45](https://user-images.githubusercontent.com/70877098/159198580-4b97aecb-46a1-4275-9d99-1bcb6359dc38.png)

**Comment by ducbm051291** [comment]
Ok, merged ;)

**Comment by minhnimble** [comment]
I notice that you have fixed most of the issues, really nice work there 🎉. On top of that, I would like to add few small problems I have:
- The page indicators are very close to the survey title on iPhone 11.
  <img src="https://user-images.githubusercontent.com/70877098/159201732-9f047fed-ffaa-499d-9aa6-70499ea5e965.PNG" width="300">

- The shimmer loading indicator doesn't look very close to the design. The design has a darker background comparing to the current implementation:
   <img src="https://user-images.githubusercontent.com/70877098/159201953-3aa00954-421a-4834-a69f-35219fa2b135.jpeg" width="300">

- When the load more call is triggered, there is no loading spinner shown to indicate about the load and there is no message for notifying if we reach the last page. Do you think it is worth letting user know about them?

https://user-images.githubusercontent.com/70877098/159202154-9beabe16-0599-4c2c-8da8-2326830ddf16.MP4

**Comment by ducbm051291** [comment]
> The page indicators are very close to the survey title on iPhone 11.
+ Ok, fixed

> The shimmer loading indicator doesn't look very close to the design. The design has a darker background comparing to the current implementation:
+ OK, fixed

> When the load more call is triggered, there is no loading spinner shown to indicate about the load and there is no message for notifying if we reach the last page. Do you think it is worth letting user know about them?
+ For this case, we can add a loading indicator in footer view to let they know we are still loading or we can add a fake item to display loading using shimmer ui. 
+ About the end of list. I rarely see any application let user know about this. Usually, user will know they reach to the end of the list when there's no loading indicator here.

**Comment by minhnimble** [comment]
Thank you for your responses. I would like to comment on your answers as follow:
> For this case, we can add a loading indicator in footer view to let they know we are still loading or we can add a fake item to display loading using shimmer ui.

→ Shimmer ui might create a blocking experience since it covers the entire screen and user can't see what happen below. A a loading indicator in footer view sounds better to me 👍

> About the end of list. I rarely see any application let user know about this. Usually, user will know they reach to the end of the list when there's no loading indicator here.

→ Yup, I agree with you on this part 👌

By reaching this far, I think you have nice responses and good implementations. 🎉 Before I end this session, I have some final questions for you:
- I saw that you have debug prints in your code. What do you think is the proper logging abstraction for a medium to large scale project?
- What do you think about the automation in projects? Do you know if there is any tool that can support automation? If yes, what is the best tool out there from your opinion? and why?
- From your experience with CI/CD, do you think CI and git workflows should be same for all the projects or do you believe that we should try to define process per project?

**Comment by ducbm051291** [comment]
> I saw that you have debug prints in your code. What do you think is the proper logging abstraction for a medium to large scale project?
+ I think that we just need os_log. It has many advantage and a lightweight and built by Apple themself that we no need Cocoapods. 

> What do you think about the automation in projects? Do you know if there is any tool that can support automation? If yes, what is the best tool out there from your opinion? and why?
+ Actually, I really never deal with any automation in my past projects. But I know some like XCTest, XCUITest, Appium... Most of them are free and proved in actual projects.

> From your experience with CI/CD, do you think CI and git workflows should be same for all the projects or do you believe that we should try to define process per project? 
+ Yes, I think CI and git workflows should be same for all the projects unless the project belong to some special cases or special requirement from customer. It's needed and should be because when we have a process that worked and everybody understand and well-known about it, there's nothing wrong trying to change it. It's said that 
> If It Ain’t Broke, Don’t Fix It
We can save time and resources to improve others stuff and new employee will be able to get used to it easily and work well effortlessly

**Comment by minhnimble** [comment]
Thanks for your reply! This ends my review for this code challenge session. For the next step, you will be hearing from the team about the decision as soon as possible. 🙏

In the end, it was a good pleasure reviewing your code and getting to know you, you have performed well. 👍 I wish you all the very best. 🍀
