### ISSUE TITLE
Testing issues

### ISSUE THREAD

**Issue by minhnimble** [ducbm051291/NimbleSurvey#5]
It is quite nice to see that you've included a few unit tests for the ViewModel layer’s logic and all of them are passed 👍. Unfortunately, right now you are putting all the test cases in one place and it is hard for me to tell which unit tests are for which ViewModel. Do you mind to organize the test cases here a little bit and group them accordingly per each ViewModel? 🙏

![Screen Shot 2022-03-17 at 14 31 48](https://user-images.githubusercontent.com/70877098/158759514-dc27e7a3-fc05-4e3b-ba5f-cf8c9ae6fc87.png)

At the same time, I would like to know if you have any experiences in any other 3rd-party library for writing tests apart from the native XCTest? If yes can you tell me a little bit more on how you would write tests using those libraries?

Lastly, I see that you didn't include any UI tests in the application. Can you add a few UI tests with some basic flow in the application? An example could be a simple flow to open the Survey Lists screen from Login screen.

**Comment by ducbm051291** [comment]
For the truth, since my graduation, althought I had learned about testing, from my first job till current I rarely have chance to write test. Almost every company I worked and am working dont require it. The deadline always win. So I tried my best to write some test cases and I think if I have any chance to learn, to know more and to apply them, I'm gonna take it.
