### ISSUE TITLE
Architecture issues

### ISSUE THREAD

**Issue by minhnimble** [ducbm051291/NimbleSurvey#6]
It is great to see you utilize the MVVM architecture with RxSwift in a quite interesting way. I do have a few small concerns on the following parts that I would love to hear more from you:
  - I see that you are creating the ViewModel's Input and Output as struct. Can you tell a bit more on why do you choose this approach? And do you know of any other technique to organize the ViewModel's 's input and output without using struct?
  https://github.com/ducbm051291/NimbleSurvey/blob/40ecbcc4266145f45c57c956351225208b0439fd/NimbleSurvey/NimbleSurvey/Modules/Home/HomeViewModel.swift#L19-L28

  - At this point, you push the `loadResult` to the `HomeViewController` but then it means that the logic for handling what to do next is being added in the View layer directly, including pushing the result back to the ViewModel layer in success case and show an error message in the failed case. In your opinion, is there any better way to handle and move this logic to ViewModel layer instead?
  https://github.com/ducbm051291/NimbleSurvey/blob/40ecbcc4266145f45c57c956351225208b0439fd/NimbleSurvey/NimbleSurvey/Modules/Home/HomeViewController.swift#L86-L96

For the data layer, I noticed that you are using Codable and parse JSON API formatted responses manually instead of using a 3rd-party library for handling this task. Why do you think parsing manually like this would be a better choice? And do you think using a JSON API parser library would add more benefits?
https://github.com/ducbm051291/NimbleSurvey/blob/40ecbcc4266145f45c57c956351225208b0439fd/NimbleSurvey/NimbleSurvey/Models/NimbleSurveyItem.swift#L10-L29

This one is more of a nitpick, but I don't see you apply Dependency Injection in the project at all and you are generating the ViewModel objects and their dependencies directly in the ViewController class. Do you think it would be better to apply Dependency Injection for this project? If yes, how and where are the most suitable places you think it would be worth applying?

**Comment by ducbm051291** [comment]
I see that you are creating the ViewModel's Input and Output as struct. Can you tell a bit more on why do you choose this approach? And do you know of any other technique to organize the ViewModel's 's input and output without using struct?
+ I chose this approach because I feel it fit with the reactive programming. In this style of programming, everything is a stream. There's always input and transformer and then output. We can use protocol instead of input and output. The typealias make this generic.

At this point, you push the loadResult to the HomeViewController but then it means that the logic for handling what to do next is being added in the View layer directly, including pushing the result back to the ViewModel layer in success case and show an error message in the failed case. In your opinion, is there any better way to handle and move this logic to ViewModel layer instead?
+ Some co-worker did advise me about this, I think that's good idea to put all the logic inside view model layeer. Because I worked with this style for a while so I didn't change it. One more thing, because I think the dispose bag should be only one and better be in view controller. 

For the data layer, I noticed that you are using Codable and parse JSON API formatted responses manually instead of using a 3rd-party library for handling this task. Why do you think parsing manually like this would be a better choice? And do you think using a JSON API parser library would add more benefits?
+ I used to use some third party like ObjectMapper but I think Apple did support this, why we don't use it, I feel it's pretty convenient and we can archive them and save them to local data. 

This one is more of a nitpick, but I don't see you apply Dependency Injection in the project at all and you are generating the ViewModel objects and their dependencies directly in the ViewController class. Do you think it would be better to apply Dependency Injection for this project? If yes, how and where are the most suitable places you think it would be worth applying?
+ You're right. This project is very small and just like a sample, so I don't think we can take advantage of DI. If we have a flow with many screen, that depency surely be injected from screen to screen in their scope.

**Comment by minhnimble** [comment]
> I used to use some third party like ObjectMapper but I think Apple did support this, why we don't use it, I feel it's pretty convenient and we can archive them and save them to local data.

→ I think you misunderstand my question a bit, since my point is mainly about handling JSON:API response format. In case you don't know what it is and why we use it, please feel free to take a look [here](https://jsonapi.org/) 🙏.
At the same time, our provided documentations suggest some iOS libraries for handling JSON:API response [here](https://jsonapi.org/implementations/#client-libraries-ios) and you probably missed that. 😅
Anyway, what do you think about updating to use a JSON:API parser instead of doing it manually with Codable like now?

**Comment by minhnimble** [comment]
> Some co-worker did advise me about this, I think that's good idea to put all the logic inside view model layeer. Because I worked with this style for a while so I didn't change it. One more thing, because I think the dispose bag should be only one and better be in view controller.

→ it sounds great to me that you agree to put the all logic inside ViewModel only and I can't wait to see how you would update this part to make this happen 👍. 
Regarding the point that the dispose bag should be only one and better be in view controller, can you tell me a little bit more on why does this has to be this way? as I believe we can still share the dispose bag of the View Controller to VM if we need to use it inside the VM, right?

> I used to use some third party like ObjectMapper but I think Apple did support this, why we don't use it, I feel it's pretty convenient and we can archive them and save them to local data.

→ I think you misunderstand my question a bit, since my point is mainly about handling JSON:API response format. In case you don't know what it is and why we use it, please feel free to take a look [here](https://jsonapi.org/) 🙏.
At the same time, our provided documentations suggest some iOS libraries for handling JSON:API response [here](https://jsonapi.org/implementations/#client-libraries-ios) and you probably missed that. 😅
Anyway, what do you think about updating to use a JSON:API parser instead of doing it manually with Codable like now?

**Comment by ducbm051291** [comment]
> Regarding the point that the dispose bag should be only one and better be in view controller, can you tell me a little bit more on why does this has to be this way? as I believe we can still share the dispose bag of the View Controller to VM if we need to use it inside the VM, right?

+ That's good, so I will pass the dispose bag to the view model

> I think you misunderstand my question a bit, since my point is mainly about handling JSON:API response format. In case you don't know what it is and why we use it, please feel free to take a look [here](https://jsonapi.org/) 🙏.

At the same time, our provided documentations suggest some iOS libraries for handling JSON:API response [here](https://jsonapi.org/implementations/#client-libraries-ios) and you probably missed that. 😅

Anyway, what do you think about updating to use a JSON:API parser instead of doing it manually with Codable like now?

Well, I just read it again and see this is totally new to me

**Comment by ducbm051291** [comment]
![Screen Shot 2022-03-17 at 19 46 42](https://user-images.githubusercontent.com/24598204/158811494-b1aeb5c6-8465-4cb2-99fb-88cbffb9432e.png)
According to JSON:API, the id field is supposed to be string but in sign in and refresh token API, it's an Int value. Is API wrong?

**Comment by minhnimble** [comment]
@ducbm051291 😁 not really, we have a fix for it in our repo here https://github.com/nimblehq/nimble-survey-web/pull/62 but our team has delayed the merging for awhile. The team should be working on getting the fix merge soon, thank you for actually raising this. 🙏 

In the meantime, you are free to explore the new JSON:API libraries and you are not required to implement them 💪. So sorry for this inconvenience 🙇‍♂️

**Comment by minhnimble** [comment]
Just for your information, the fix for the id field is just merged and deployed. You are good to play with the JSON:API libraries via our API endpoints now 🚀

**Comment by minhnimble** [comment]
Looks good to me for this issue, closing it now 👍

**Comment by minhnimble** [comment]
> > Regarding the point that the dispose bag should be only one and better be in view controller, can you tell me a little bit more on why does this has to be this way? as I believe we can still share the dispose bag of the View Controller to VM if we need to use it inside the VM, right?
> 
>     * That's good, so I will pass the dispose bag to the view model
> 
> 
> > I think you misunderstand my question a bit, since my point is mainly about handling JSON:API response format. In case you don't know what it is and why we use it, please feel free to take a look [here](https://jsonapi.org/) 🙏.
> 
> > At the same time, our provided documentations suggest some iOS libraries for handling JSON:API response [here](https://jsonapi.org/implementations/#client-libraries-ios) and you probably missed that. 😅
> 
> > Anyway, what do you think about updating to use a JSON:API parser instead of doing it manually with Codable like now?
> 
>     * Well, I just read it again and see this is totally new to me. Sure I will give it a try
